FROM openjdk:8-jdk-alpine

ENV ELASTIC_APM_VERSION "1.8.0"
RUN wget -O /apm-agent.jar https://search.maven.org/remotecontent?filepath=co/elastic/apm/elastic-apm-agent/$ELASTIC_APM_VERSION/elastic-apm-agent-$ELASTIC_APM_VERSION.jar
COPY target/javalin-student-1.0-SNAPSHOT.jar /app.jar

# COPY target/spring-boot-simple.jar /app.jar
EXPOSE 8080
CMD java -jar /app.jar


# FROM openjdk:8-jdk-alpine
# VOLUME /tmp
# ARG JAVA_OPTS
# ENV JAVA_OPTS=$JAVA_OPTS
# ADD out/artifacts/javalin_student_jar/javalin-student.jar javalin-student.jar
# EXPOSE 8080
# ENTRYPOINT exec java $JAVA_OPTS -jar javalin-student.jar
# For Spring-Boot project, use the entrypoint below to reduce Tomcat startup time.
#ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar javalin-student.jar