apiVersion: v1
kind: ConfigMap
metadata:
  namespace: log
  name: apm-server-config
  labels:
    app: apm-server
data:
  apm-server.yml: |-
    apm-server:
      host: "0.0.0.0:8200"

    output.elasticsearch:
      hosts: ['elasticsearch.log.svc.cluster.local.:9200']

---

# hosts: ['http://logs.non-prod.homelane.com:7070']
#       username: elastic
#       password: M0sZfTj47u7ONuKx8pyN

---
apiVersion: v1 
kind: Service 
metadata: 
  name: apm-server
  labels:
    app: apm-server
spec: 
  type: ClusterIP
  ports: 
  - protocol: TCP 
    port: 8080 
    targetPort: 8080 
  selector: 
    app: apm-server
